name: app
description: "A new Flutter project."
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter
  meta: ^1.16.0
  flutter_riverpod: ^2.6.1
  get_it: ^8.2.0
  logger: ^2.6.1
  dio: ^5.9.0
  flutter_dotenv: ^6.0.0
  intl: ^0.20.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  # Added for Lead Image Management
  dartz: ^0.10.1
  connectivity_plus: ^6.0.5
  uuid: ^4.5.1
  image: ^4.3.0
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  go_router: ^14.6.2
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  path_provider: ^2.1.5

dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  asset_fill: ^2.0.0
  build_runner: ^2.7.0
  json_serializable: ^6.10.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  # Freezed code generation
  freezed: ^3.2.0
  # Testing
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/
    - assets/brand/
    # - assets/images/
    # - myenv
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/Manrope-VariableFont_wght.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-VariableFont_wght.ttf
        - asset: assets/fonts/Nunito/Nunito-Italic-VariableFont_wght.ttf
          style: italic
    - family: InstrumentSans
      fonts:
        - asset: assets/fonts/InstrumentSans/InstrumentSans-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/InstrumentSans/InstrumentSans-Italic-VariableFont_wdth,wght.ttf
          style: italic
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-VariableFont_wght.ttf
