name: app
description: "A new Flutter project."
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter
  dotted_border: ^3.1.0
  http: ^1.5.0
  meta: ^1.16.0
  flutter_riverpod: ^2.6.1
  get_it: ^8.2.0
  go_router: ^16.2.0
  flutter_animate: ^4.5.2
  icons_plus: ^5.0.0
  json_serializable: ^6.10.0
  logger: ^2.6.1
  dio: ^5.9.0
  flutter_dotenv: ^6.0.0
  intl: ^0.20.2
  flutter_native_splash: ^2.4.6
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  skeletonizer: ^2.1.0+1
  image: ^4.5.4
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  exif: ^3.3.0
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  asset_fill: ^2.0.0
  build_runner: ^2.7.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.5.0
  # Freezed code generation
  freezed: ^3.2.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/brand/
    # - assets/images/
    # - myenv
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/Manrope-VariableFont_wght.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-VariableFont_wght.ttf
        - asset: assets/fonts/Nunito/Nunito-Italic-VariableFont_wght.ttf
          style: italic
    - family: InstrumentSans
      fonts:
        - asset: assets/fonts/InstrumentSans/InstrumentSans-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/InstrumentSans/InstrumentSans-Italic-VariableFont_wdth,wght.ttf
          style: italic
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-VariableFont_wght.ttf
